parameters:
#    cocar.example.class: Cocar\CocarBundle\Example

services:
#    cocar.example:
#        class: %cocar.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

#services:
#    cocar_graph:
#        class: Cocar\CocarBundle\Controller\GraphController
services:
    cocar_monitor:
        class: GerenciadorRedes\Bundle\CocarBundle\Controller\MonitorController
    circuit:
        class: GerenciadorRedes\Bundle\CocarBundle\Entity\Circuits