<?php

namespace GerenciadorRedes\Bundle\CocarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CircuitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomCircuitsRepository extends EntityRepository
{
	public function findCircuitsBy($codeInterface, $ipBackbone)
	{
		return $this->getEntityManager()
        	->createQuery(
            	"SELECT c FROM CocarBundle:Circuits c 
            		WHERE c.codeInterface = :cod
            			AND c.ipBackbone = :ip
            			AND c.status = :status
            			AND c.generateAlarm = :alarm"
        	)
        	->setParameter('cod', $codeInterface)
        	->setParameter('ip', $ipBackbone)
        	->setParameter('status', 'UP')
        	->setParameter('alarm', true)
        	->getResult();
	}
}