<?php

namespace GerenciadorRedes\Bundle\CocarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MonthlyPerformanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonthlyPerformanceRepository extends EntityRepository
{
}
